### ISSUE TITLE
SAMD51 Support

### ISSUE THREAD

**Issue by ghost** [BriscoeTech/Arduino-FreeRTOS-SAMD21#14]
@BriscoeTech First of all I'd like to say thank you very much for your SAMD21 port of FreeRTOS and making it available.

It's not an issue really, it's just that Adafruit have now realeased a number of new SAMD51 based Arduino compatible boards. I've managed to get your FreeRTOS port to work on an 120MHz Adafruit Itsy Bitsy M4 board simply by changing the _configCPU_CLOCK_HZ_ definition from _48000000_ to _F_CPU_ in the "FreeRTOSConfig.h" file.

```
#define configCPU_CLOCK_HZ				( ( unsigned long ) F_CPU )
```
So far I've managed to test FreeRTOS tasks, queues, software timers and hardware interrupt managment and currently all seems to be working OK. 

Using F_CPU seems to allow use of both the SAMD21 at 48MHz (on my Arduino Zero) and the SAMD51 at 120MHz, as well as possibly the SAMD51's overclocking options of 150, 180 and 200MHz (should anyone be brave enough to try them?).

**Comment by BriscoeTech** [comment]
Hello @MartinL1

Thanks for posting! I have been wondering how painful the move to the samd51 would be, glad to hear it isn't. :-) I do not have a board yet, but am thinking of getting one very soon to play with.

I will make this change in my next commit, thanks!

**Comment by BriscoeTech** [comment]
After poking around on some code today, I forgot I implemented a vNopDelayMS in the errorHooks.h and errorHooks.c functions, and it assumes a constant scale factor to figure out the number of noops needed achieve a millisecond delay.

I should probably put a typedef into this file, and depending on the processor used select the correct cal factor.

I am wonder if the samd51 needs a different scale factor, there architecture seems very similar they probably implement the noop in the same number of clock cycles on both.

@MartinL1 If you get a chance since you have the hardware, I would love to know if vNopDelayMS(1000) in a simple blink rtos program seems like it is still about a second. Looks like I have no excuse to buy a board now :-P

Thanks! Talk to you soon!

**Comment by ghost** [comment]
> If you get a chance since you have the hardware, I would love to know if vNopDelayMS(1000) in a simple blink rtos program seems like it is still about a second. Looks like I have no excuse to buy a board now :-P

@BriscoeTech I've run the following task on my Adafruit Itsy Bitsy M4 and can confirm that it operates correctly, blinking on and off at 1 second intervals:

```
void TaskBlink(void *pvParameters)
{
  pinMode(13, OUTPUT);        // Initialise D13 as an output

  for (;;)                    // Endless loop
  {
    digitalWrite(13, HIGH);   // Turn LED on
    vNopDelayMS(1000);        // Wait for one second
    digitalWrite(13, LOW);    // Turn LED off
    vNopDelayMS(1000);        // Wait for one second
  }
}
```

**Comment by BriscoeTech** [comment]
Hello @MartinL1 

Good to hear! I merged this change to the master brach and it is now apart of v1.0.0. 

I made the clock speed change you recommended. I also added some code to error_hooks.h to check the processor type and select the proper cal factor for turning clock speed to proper number of noops. This is more for the future, in case a new chip arrives thats noop is a different number of clock cycles than the samd21/51.

I also updated the readme so that people are aware it will work with the Samd51.

Thanks again!
