### ISSUE TITLE
Static allocation only

### ISSUE THREAD

**Issue by gpelizzo** [BriscoeTech/Arduino-FreeRTOS-SAMD21#26]
Hi,
After having set configSUPPORT_STATIC_ALLOCATION to 1 and reset configSUPPORT_DYNAMIC_ALLOCATION to 0, an update with the static methods, compilator raises multiple errors, e.g.:

-----------------------------------------------------------------
Compiling ...\lib2ff\FreeRTOS_SAMD21\timers.c.o
  #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0

--------------------------------------------------------------
...\FreeRTOS_SAMD21\src\heap_4bis.c:49:3: error: #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0
  #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0

Regards

**Comment by BriscoeTech** [comment]
Yes, this is not a issue with this library. This looks more like a FreeRtos feature.

It looks like these are error messages were defined in those files by the FreeRtos team because they don't belong with the settings you set. You should delete those files and remove them from linking to prevent those error messages.

**Comment by gpelizzo** [comment]
Perfect. Thanks
