### ISSUE TITLE
Serial access not protected against multiple calls from different threads

### ISSUE THREAD

**Issue by nanosonde** [BriscoeTech/Arduino-FreeRTOS-SAMD21#4]
Hi!

I have just looked into the provided example "Basic:_RTOS_Example".
I wonder how this can work if the access to the serial port is not synchronized somehow by using a mutex for example. Each thread just uses the the normal Serial.println() method.
As your FreeRTOS config uses preemptive multitasking, I think that you might easily run into trouble in this case.

IMHO, the serial access needs some mutex locking to provide a proper solution.

**Comment by BriscoeTech** [comment]
Hello nanosonde,

Very astute observation, I too though the same thing when I was first porting freertos over :-).

For awhile I was using someone else port to the atmega328, and serial was not mutexed and I learned very quickly it would fail hard and fast and would lockup the device. I had that mindset going into this port, and it was on my todo list until I noticed I was not running into any issues.

I have not delved to deep into it, but it appears the arduino samd21 implementation of serial is actually atomic. My guess is that the hardware allows for the buffering of quite afew more bytes that a Atmega, and the shoving of the bytes to the hardware is a single operation. 

I am developing an application right now and I have about 10 threads + idle thread all running, and all writing debug information to the serial display... pretty much constantly. I am not running into any lockups, and chars between print statements are not being interleaved. Print statements from one task to the next could be interleaved, but this can all be explained by my task delays, scheduling, and preemption by design.

I can see that if you had a thread that needed to perform multiple serial.print commands, and you had to guarantee if finished and prevent the interleaving of other threads prints, then I would recommend implementing a mutex to meet your design requirement. As far as system stability goes, the mutex is not needed and serial can be used without worry as a debug terminal.

I think I will leave that up to the user if they feel the need to implement a mutex.  If anyone finds a instance where the hardware locks up because of this, then you can easily change my mind ;-)

Thanks for posting!

**Comment by nanosonde** [comment]
Ok, thanks for quick reply. Having not looked into the arduino code yet, I hope that all the arduino core functions are reentrant at least using on-stack local variables.
